name: colored
description: A Flutter application that helps designers and developers work with colors.
version: 0.9.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  expandable_slider: ^1.0.3
  cupertino_icons: ^0.1.2
  vector_math: ^2.0.8
  collection: ^1.14.11
  shared_preferences: ^0.5.6+3
  transparent_image: ^1.0.0
  smooth_page_indicator: ^0.1.5
  mockito: ^4.1.1
  auto_size_text: ^2.1.0
  http: ^0.12.1
  animations: ^1.0.0+5
  async: ^2.4.1
  connectivity: '>=0.4.8+6 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/resources/fonts/montserrat/Montserrat-Regular.ttf
        - asset: lib/resources/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: lib/resources/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Oswald
      fonts:
        - asset: lib/resources/fonts/oswald/static/Oswald-Regular.ttf
        - asset: lib/resources/fonts/oswald/static/Oswald-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/oswald/static/Oswald-SemiBold.ttf
          weight: 600

  assets:
    - lib/resources/graphics/
    - lib/resources/mock_data/
    - lib/resources/data/
