name: colored
description: A Flutter application that helps designers and developers work with colors.
version: 0.11.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animations: ^2.0.0
  async: ^2.5.0
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  expandable_slider: ^2.0.0
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.1
  keyboard_dismisser: ^2.0.0
  mockito: ^5.0.5
  shared_preferences: ^2.0.5
  smooth_page_indicator: ^0.3.0-nullsafety.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.3
  vector_math: ^2.1.0

dev_dependencies:
  dart_code_metrics: ^4.6.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/resources/fonts/montserrat/Montserrat-Regular.ttf
        - asset: lib/resources/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: lib/resources/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Oswald
      fonts:
        - asset: lib/resources/fonts/oswald/static/Oswald-Regular.ttf
        - asset: lib/resources/fonts/oswald/static/Oswald-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/oswald/static/Oswald-SemiBold.ttf
          weight: 600

  assets:
    - lib/resources/graphics/
    - lib/resources/mock_data/
    - lib/resources/data/
