name: CI

on: pull_request
    
jobs:
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    env: 
      working-directory: code
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        path: ${{env.working-directory}}

    - name: Set up Flutter environment
      uses: subosito/flutter-action@v1
      with:
         channel: 'stable'
    
    - name: Get Flutter packages
      run: flutter pub get
      working-directory: ${{env.working-directory}}

    - name: Check formatting
      run: flutter format --set-exit-if-changed .
      working-directory: ${{env.working-directory}}
    
    - name: Analyze project
      run: flutter analyze .
      working-directory: ${{env.working-directory}}
    
    - name: Run tests with coverage
      run: flutter test --coverage
      working-directory: ${{env.working-directory}}

    - name: Check code coverage
      uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
      with:
        path: '${{env.working-directory}}/coverage/lcov.info'
        min_coverage: 95
    
